name: combos_example
description: Example App for 'combos' package

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  combos: any
  editors: ^0.0.2+4
  demo_items:
    git: https://github.com/creomobile/demo_items

dependency_overrides:
  combos:
    path: ../

dev_dependencies:
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
