name: combos
description: Combo Widgets for Flutter. Includes Combo, AwaitCombo, ListCombo, SelectorCombo, TypeaheadCombo, MenuItemCombo
version: 1.0.0+1
homepage: https://github.com/creomobile/combos

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
